### PR TITLE
Compiled for Rimworld 1.5

### PR DESCRIPTION
**Pull request by chill0r**
Tested and working.

### CODE REVIEW

**Comment by notfood** [comment]
Getting rid of the `Krafs.Rimworld.Ref` is a nono. Does it only need a recompile? Huh...

**Comment by notfood** [comment]
Here https://github.com/notfood/RimWorld-Infused/commit/ea65ec8ad627221c2c4faafb2d2d733628a0a12f

**Comment by chill0r** [comment]
I removed ```Krafs.Rimworld.Ref``` and used the original games dlls instead since when compiled with it (on my end) screen stuttering occurred (I used the latest version from NuGet).
Maybe they updated the nuget version in the meantime if it works now

**Comment by notfood** [comment]
Stuttering sounds completely unrelated. Logs would have been a good start to debug it, probably erroing nonstop because wrong version targetted.

**Pull request closed without merging**
